### ISSUE TITLE
Unban account

### ISSUE THREAD

**Issue by Dr-Wily** [barronwaffles/dwc_network_server_emulator#296] opened 2016-05-23 09:46 UTC
I succesfully connected 12 Wii for a for a Mario Katr Wii LAN. The connection is perfect and all machine hooks others correctly. (https://fr-fr.facebook.com/simms.club/videos/vb.147584932006102/925988427499078/?type=2&theater)

However, there is an annoying behaviour. From time to time some accounts are banned with 61xxx error code. Logs on server shows blocked=1, but there is no banned account in database. So, that means I must delete license, recreate it and enter friend code with 12 others Wii.

How to unban this blocked account ?

**Comment by kyle95wm** [comment] 2016-05-23 09:51
This is still a known issue/bug. The best thing to do is not add friends in games. Maybe someone can chime in here with a better solution.

**Comment by Dr-Wily** [comment] 2016-05-23 10:07
Yes, but the only fastest way to gather 12 players in same game is to use friend code. Worldwide game works also, but it split players in multiples games rooms. In worldwide game all players must enter at the same time and be lucky enough to meet each others... not very convinient...

Most of time friend code works. But I want to understand where is stored the "blocked" information. In the savegame or in database ? Logs shows "blocked = 1" but in which database I can find this information ?

There is no information on DB files used by altwfc.

**Comment by sepalani** [comment] 2016-05-23 11:36
You can interact with the database in a pythonic way like altwfc does by opening an interactive python shell and instantiating a GamespyDatabase() class. Then you can call the appropriate method to edit the profile in the database. They're documented in the python file that you can open with a notepad.

``` bash
python -i gamespy/gs_database.py
```

``` python
db = GamespyDatabase()
db.the_method_that_suits_your_needs(the_appropriate_parameters)
```

**EDIT:** It seems what you're looking for is in gpcm.db in the buddies table.

**Comment by sepalani** [comment] 2016-05-23 12:02
@Dr-Wily 
Could you also post the complete logs of the session where it happened. By the way, which version of altwfc were you using?

**Comment by Dr-Wily** [comment] 2016-05-23 13:33
Thank selpani ! Yes I can post the logs. At this time the server is off, but I will upload these later. I use the version before the natneg rewriting.

**Comment by Dr-Wily** [comment] 2016-05-23 20:03
Thank selpani ! Yes I can post the logs. At this time the server is off, but I will upload these later. I use the version before the natneg rewriting.

EDIT :
You can donwload the complete logs here : http://wellby.dyndns.org/dnl/altwfc-log-201605.zip

Don't bother with date. The server battery is low and do not keep time after power off.

All logs in zip contain 3 days off non stop gaming.

**Comment by sepalani** [comment] 2016-07-06 05:34
@Dr-Wily 
Sorry to be that late. I checked in the database you gave and no account is either banned or blocked. I guess the message you saw in logs with "blocked = 1" were the "SQL-like" SELECT requests to check if such user is blocked or not. I didn't find any UPDATE request that change the value of banned or blocked neither.

Is there a way to reproduce that issue?

According to the [Wiimmfi error code list](http://forum.wii-homebrew.com/index.php/Thread/51738-Collecting-Error-Codes/), 61XXX error code is a GP(CM?) server error. Which make more sense because I don't remember altwfc throwing that error and didn't see anything abnormal in the database.

**Comment by Dr-Wily** [comment] 2016-07-06 09:02
Yes, I also reached the same conclusions. Like you I don't understand why I saw blocked=1 and no banned account in DB (described on my first post). But, I can describe the behaviour when an account is blocked/banned.
- it occurs only when using friends codes and private game room.
- the error occurs when a friend can't join the game room opened by other friend OR when the player is disconnected during the game.
- after that, when you try to reconnect to WFC, game gives an 61xx error and it's impossible to reconnect. Even if I make a complete reset of the Wii.

Maybe the "blocked" information is stored in savegame ?

The same behavior happens on Mario kart DS, in the same ways. I must delete WFC information for reconnect it on alwfc server.

**Comment by sepalani** [comment] 2016-07-06 10:23
Have you tried to reboot the server? It might be a session problem.

**EDIT:** It remembers me a similar issue I have randomly when the nas server randomly ignored HTTP requests.

**Comment by sepalani** [comment] 2016-07-06 11:55
Does this also occur with the latest version of altwfc ?

**Comment by Dr-Wily** [comment] 2016-07-06 13:11
Yes, reboot the server give no change. Sames accounts can't connect.

With the latest version of altwfc I had 61xx 2 time. I have the log from latest version of the server, do you want them?

The common element between 2 servers is the DB files.

**Comment by sepalani** [comment] 2016-07-07 05:32
Those might help. Do you have the profile FC or pid raising that error?

**Comment by Dr-Wily** [comment] 2016-07-11 17:12
You can look at logs [here](http://wellby.dyndns.org/dnl/altwfc-log-ds.zip)

**Comment by sepalani** [comment] 2016-07-12 06:01
I figured out something interesting. Just to be sure, I would like you to backup your logs and only send me log files that appear when the login fails.

The game itself seems to force the logout. In your logs:

The session key is:

> SENDING: \lc\2\sesskey\**02603454**\proof\daa9a7687017f3daeca5d88c0093b18f\userid\1374716109071\profileid\45\uniquenick\1809ne88fAMCJ3612p6g\lt\T1Bob2RXbTg5ZFZWNVdJQQ__\id\1\final\

The session key the game sent is stripped:

> RESPONSE: '\status\1\sesskey\**2603454**\statstring\locstring\final\'

In the others logs you sent me the sesskey isn't stripped. I don't know what impacts it can have, I'll investigate further when I'll the time. I guess if the db store the sesskey as string, it won't be able to delete the session.

**Closed as completed** 2019-03-07 05:26 UTC
Labels: wontfix
